CON_PORT: RiCBoard
FILE_NAME: komodo
URF0/publishHz: 20
URF0/name: left_urf
URF0/frameId: Left_URF_link
URF0/type: 10
URF0/port: 1
URF1/publishHz: 50
URF1/name: rear_urf
URF1/frameId: Rear_URF_link
URF1/type: 10
URF1/port: 2
URF2/publishHz: 50
URF2/name: right_urf
URF2/frameId: Right_URF_link
URF2/type: 10
URF2/port: 3
closeLoop0/publishHz: 20
closeLoop0/name: left_motor
closeLoop0/LPFAlpha: 0.7
closeLoop0/LPFHz: 50
closeLoop0/driverAddress: 999
closeLoop0/channel: 0
closeLoop0/port: 1
closeLoop0/PIDHz: 1000
closeLoop0/kP: 50.0
closeLoop0/kI: 55.0
closeLoop0/kD: 0
closeLoop0/limit: 1.0
closeLoop0/maxSpeed: 16.0
closeLoop0/cpr: 2503
closeLoop0/timeout: 1000
closeLoop0/motorType: 1
closeLoop0/encoderType: 1
closeLoop0/direction: 1
closeLoop0/directionE: -1
closeLoop1/publishHz: 20
closeLoop1/name: right_motor
closeLoop1/LPFAlpha: 0.7
closeLoop1/LPFHz: 50
closeLoop1/driverAddress: 999
closeLoop1/channel: 1
closeLoop1/port: 2
closeLoop1/PIDHz: 1000
closeLoop1/kP: 50.0
closeLoop1/kI: 55.0
closeLoop1/kD: 0
closeLoop1/limit: 1.0
closeLoop1/maxSpeed: 16.0
closeLoop1/cpr: 2503
closeLoop1/timeout: 1000
closeLoop1/motorType: 1
closeLoop1/encoderType: 1
closeLoop1/direction: 1
closeLoop1/directionE: 1
Diff/publishHz: 50
Diff/name: diff_driver
Diff/rWheel: 0.1311
Diff/width: 0.396
Diff/baseLink: base_link
Diff/odom: odom_link
Diff/slip: 0.65
Diff/maxAng: 16.0
Diff/maxLin: 16.0
Diff/motorL: 0
Diff/motorR: 1
IMU/publishHz: 20
IMU/name: imu
IMU/frameId: RiC_Frame
IMU/camp: 0
IMU/orientation: 0
IMU/fusionHz: 50
IMU/fuseGyro: 0
IMU_INIT: 1
GPS_INIT: 0
PPM_INIT: 0
BAT_INIT: 0
DIFF_INIT: 1
DIFF_INIT_OP: 0
DIFF_CLOSE_FOUR: 0
closeLoopNum: 2
switchNum: 0
servoNum: 0
relayNum: 0
URFNum: 3
openLoopNum: 0
emergencySwitchNum: 0
