  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20  
  
  # Position Controllers ---------------------------------------
   
  elevator_controller:
     type: effort_controllers/JointPositionController
     joint: elevator_joint
     pid: {p: 3000.0, i: 3000.0, d: 0}
     i_clamp: 10.0
  
  base_rotation_controller:
    type: effort_controllers/JointPositionController
    joint: base_rotation_joint
    pid: {p: 5.0, i: 0.1, d: 0}
  shoulder_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
  elbow1_controller:
    type: effort_controllers/JointPositionController
    joint: elbow1_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
  elbow2_controller:
    type: effort_controllers/JointPositionController
    joint: elbow2_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
  wrist_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_joint
    pid: {p: 1.0, i: 0.01, d: 0.0}
  left_finger_controller:
    type: effort_controllers/JointPositionController
    joint: left_finger_joint
    pid: {p: 0.4, i: 0.01, d: 0.0}
  right_finger_controller:
    type: effort_controllers/JointPositionController
    joint: right_finger_joint
    pid: {p: 0.4, i: 0.01, d: 0.0}
  

